// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3FBx1mjvrjHdHFL2qqOhITEZApUpTPo',
    appId: '1:502798895838:web:8860d6ee01a94e6f4c104f',
    messagingSenderId: '502798895838',
    projectId: 'schoolapp-70a66',
    authDomain: 'schoolapp-70a66.firebaseapp.com',
    databaseURL: 'https://schoolapp-70a66-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-70a66.appspot.com',
    measurementId: 'G-X38535LKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDmtHqmf9Q7NtEhcY0gcDZVyhduJXLhw',
    appId: '1:502798895838:android:a897312b9156b3514c104f',
    messagingSenderId: '502798895838',
    projectId: 'schoolapp-70a66',
    databaseURL: 'https://schoolapp-70a66-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-70a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykGspNTCs-HMUr3UBInvHflr3JicOeR4',
    appId: '1:502798895838:ios:0e11af9de880d9d04c104f',
    messagingSenderId: '502798895838',
    projectId: 'schoolapp-70a66',
    databaseURL: 'https://schoolapp-70a66-default-rtdb.firebaseio.com',
    storageBucket: 'schoolapp-70a66.appspot.com',
    iosClientId: '502798895838-473c71utd92tgtc1ipobgg793smc0qlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.backendSchool',
  );
}
